//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPropietaria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContabilidadEntities : DbContext
    {
        public ContabilidadEntities()
            : base("name=ContabilidadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account_types> account_types { get; set; }
        public virtual DbSet<countables_accounts> countables_accounts { get; set; }
        public virtual DbSet<currencies_types> currencies_types { get; set; }
        public virtual DbSet<logs> logs { get; set; }
        public virtual DbSet<parameters> parameters { get; set; }
        public virtual DbSet<placements> placements { get; set; }
        public virtual DbSet<placements_movements> placements_movements { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<wholesale> wholesale { get; set; }
    }
}
