//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPropietaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class logs
    {
        public int id { get; set; }
        public string data { get; set; }
        public int action { get; set; }
        public bool success { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> user { get; set; }
    
        public virtual users users { get; set; }
    }
}
