//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPropietaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class parameters
    {
        public int id { get; set; }
        public int year { get; set; }
        public int month { get; set; }
        public string processed { get; set; }
        public string rnc { get; set; }
        public int month_close { get; set; }
    }
}
