//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPropietaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class placements_movements
    {
        public int id { get; set; }
        public int account { get; set; }
        public string movement_type { get; set; }
        public decimal amount { get; set; }
        public int placement_id { get; set; }
    
        public virtual countables_accounts countables_accounts { get; set; }
        public virtual placements placements { get; set; }
    }
}
