//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPropietaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class placements
    {
        public int id { get; set; }
        public string description { get; set; }
        public string identifier { get; set; }
        public bool allow_transaction { get; set; }
        public string movement_type { get; set; }
        public Nullable<int> date { get; set; }
        public decimal amount { get; set; }
        public string state { get; set; }
    }
}
