//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPropietaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class wholesale
    {
        public int id { get; set; }
        public int major_account { get; set; }
        public string type_movement { get; set; }
        public System.DateTime process_date { get; set; }
        public decimal balance { get; set; }
        public string state { get; set; }
    
        public virtual countables_accounts countables_accounts { get; set; }
    }
}
